#!/usr/bin/env bash

set -euo pipefail

main() {
	local namespace=production

	# TODO: replace the project with your project ID
	echo "Authenticating gcloud service account"
	gcloud auth activate-service-account \
		--key-file /home/runner/auth.json \
		--project semaphore-gke-tutorial \

	echo "Authenticating to GCR"
	gcloud docker --authorize-only --project semaphore-gke-tutorial

	echo "Configuring kubectl"
	gcloud container clusters get-credentials demo \
		--project semaphore-gke-tutorial \
		--zone europe-west1-b

	docker-compose build
	docker-compose push

	kubectl apply -f k8s/production-namespace.yml --namespace "${namespace}"

	kubectl apply -f k8s/production-redis-service.yml --namespace "${namespace}"
	kubectl apply -f k8s/production-server-service.yml --namespace "${namespace}"

	kubectl apply -f k8s/production-redis-pod.yml --namespace "${namespace}"
	kubectl apply -f k8s/production-server-deployment.yml --namespace "${namespace}"
	kubectl apply -f k8s/production-support-deployment.yml --namespace "${namespace}"

	kubectl get pods --namespace "${namespace}"
}

main "$@"
