#!/usr/bin/env bash

set -euo pipefail

# Pre-req for gcloud install
sudo apt-get update
sudo apt-get install -y apt-transport-https

# Copied from the official install instructions on https://cloud.google.com/sdk/downloads#apt-get
export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
echo "deb https://packages.cloud.google.com/apt ${CLOUD_SDK_REPO} main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-get update
sudo apt-get install -y google-cloud-sdk kubectl

gcloud --version
kubectl version
docker-compose --version
